project:
  type: website

website:
  title: "Quarto Simple Example"
  repo-url: https://github.com/perellonieto/quarto_simple_example
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - calibration/calibration.qmd
      - about.qmd
    
  page-footer:
    left: |
      Copyright 2023, Miquel Perello Nieto.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    toc: true
    downloads: [pdf, docx]
    code-fold: true
    html-math-method: katex
    page-layout: full
    grid:
      sidebar-width: 500px
  revealjs:
    smaller: true
    scrollable: true
    logo: "images/TAILOR logo - full-color rgb.svg"
    footer: "These slides are part of a MOOC on Trustworthy AI by The TAILOR Network"
    center: true
    slide-number: true
    incremental: true
    number-depth: 2
    slide-level: 3
    show-slide-number: "all"
    #  pdf:
    #    geometry: 
    #      - top=30mm
    #      - left=30mm
    #  docx: default
