project:
  type: website

website:
  title: "Quarto Simple Example"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: |
      Quarto Simple Example is written by Miquel Perello Nieto.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    toc: true
