---
title: "Home"
author: "Miquel Perello-Nieto"
date: "March 29, 2023"
jupyter: python3
bibliography: references.bib
---

# Introduction {.unnumbered}

This is a reference @sokol2021you

# Callout notes

There are five types of call out notes, which can even hide the content

::: {.callout-note}
# You can add a title to the note with a hastag #
This is a note callout
:::

::: {.callout-tip}
This is a tip callout
:::

::: {.callout-warning}
This is a warning callout
:::

::: {.callout-caution}
This is a caution callout
:::

::: {.callout-important}
This is a important callout
:::


It is possible to modify the callout including different header text, and
hidding the content in a foldable box.

::: {.callout-note}
# You can add a title to the note with a hastag \#
This is a note callout with a different title
:::

::: {.callout-tip collapse="true"}
# You can hidde the content with collapse="true"
This is a note callout with a different title and collapsed.
:::



# Maths and equations

$E = m \cdot c^2$

# Python plots

```{python}
import matplotlib.pyplot as plt

plt.plot([0, 1, 2, 3], [1, 3, 2, 5])
```

# Inline runnable code

It is possible to run code from the same browser using Thebe, which starts a
kernel in MyBinder and is able to run the provided code. It requires the
activation of the kernel via a button, and then the code in the text cell can
be changed and run.

<!-- Configure and load Thebe !-->
<script type="text/x-thebe-config">
  {
    requestKernel: true,
    binderOptions: {
      repo: "binder-examples/requirements",
    },
  }
</script>
<script src="https://unpkg.com/thebe@latest/lib/index.js"></script>


<div class="thebe-activate"></div>

<div class="thebe-status"></div>

<pre data-executable="true" data-language="python" style="background:#BBB">
%matplotlib inline
import matplotlib.pyplot as plt

plt.plot([0, 1, 2, 3], [1, 3, 2, 5])
</pre>

The previous button is the default, provided via a div class, but it can be
adjusted as desired.

<script>
var bootstrapThebe = function() {
    thebelab.bootstrap();
}
document.querySelector("#activateButton").addEventListener('click',
bootstrapThebe)
</script>

<button id="activateButton"  style="width: 100px; height: 30px; font-size:
1em;">Start</button>



# References
